name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  logger: any
  dio: any
  floor: any
  badges: ^2.0.2
  need_resume: ^1.0.6
  provider: any


  flutter:
    sdk: flutter
  cupertino_icons: any
  page_transition: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: ^0.9.2
  floor_generator: any
  build_runner: any
  test: any
  mockito: ^5.0.16

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/shoppeicon.png"
flutter:
  assets:
    - images/cart7.png
  uses-material-design: true
  fonts:
    - family: WhiteDream
      fonts:
        - asset: fonts/whitedream.otf
